[PE-1779] add retry in case of inserter failure
ROKT/protoconf pull request #28
Opened 2024-04-08 15:59 UTC by avivl

Add retry for k8s calls in inserter

2024-04-08 17:14 UTC, spenrose approved these changes

2024-04-09 00:40 UTC, smintz requested changes
I am not familiar with this retry mechanism, so I might be wrong on my assumptions, but, from what I noticed:
- There is no limit on how many retries
- There is no indication or log something happened
- There is no validation for the type of error (should we retry if context canceled?)
This means if something is wrong, this will go to endless loop without any indication to the caller.
I think its better to move the retry mechanism to the inserter/agent and not to implement it on the KV level.
thoughts?
I am usually using this library: https://pkg.go.dev/github.com/avast/retry-go

2024-04-09 13:06 UTC, avivl commented
> I am not familiar with this retry mechanism, so I might be wrong on my assumptions, but, from what I noticed:
> 
> * There is no limit on how many retries
> * There is no indication or log something happened
> * There is no validation for the type of error (should we retry if context canceled?)
> 
> This means if something is wrong, this will go to endless loop without any indication to the caller. I think its better to move the retry mechanism to the inserter/agent and not to implement it on the KV level. thoughts? I am usually using this library: https://pkg.go.dev/github.com/avast/retry-go

-  There is no limit on how many retries - `var DefaultRetry = wait.Backoff{
	Steps:    5,
	Duration: 10 * time.Millisecond,
	Factor:   1.0,
	Jitter:   0.1,
}`

- I'll add logs
- There is no validation for the type of error (should we retry if context canceled?) this is only for errors returned from k8s.

I prefer to use k8s retry and not an external library

2024-04-09 14:29 UTC, smintz requested changes
few nits

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +		return err != context.Canceled
nit: `return !errors.Is(err, context.Canceled)`

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +			logger.Debug("Error getting configmap -retrying", slog.Any("error", err))
nit: This will also be printed after the last attempt, maybe move to `retryableFn` ?

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +		logger.Debug("Error getting configmap - after retries", slog.Any("error", retryErr))
log level should be `Error` as this is not recovering and need to be noted.

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +			logger.Debug("Error getting configmap -retrying", slog.Any("error", err))
Same question as above, this will be printed after last attempt.

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +		logger.Debug("Error getting configmap - after retries", slog.Any("error", retryErr))
Change log level to `Error`

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +	var err error
This is not required, `retryErr` provides same functionality.

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +		logger.Debug("Error Watching configmap - after retries", slog.Any("error", retryErr))
rasie level to `Error`

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
>  	}
This is not required, as `retryErr` provides same.

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +		if retryErr != nil {
add log

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +		return err != context.Canceled
use `errors.Is`

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +		return err != context.Canceled
use `errors.Is`

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +		logger.Debug("Error updating configmap - after retries", slog.Any("error", retryErr))
set log level to `Error`

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +		return err != context.Canceled
use `errors.Is`

2024-04-09 14:29 UTC, smintz commented on agent/configmaps/configmaps.go
> +		return err != context.Canceled
Also, this function is been declared over and over again, can DRY

2024-04-10 01:15 UTC, smintz approved these changes

2024-04-10 12:46 UTC, merged